# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
# deployments.apps "plus-nap-kic-nginx-ingress" was not valid:
# * : Invalid value: "The edited file failed validation": ValidationError(Deployment.spec): unknown field "hostNetwork" in io.k8s.api.apps.v1.DeploymentSpec
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    meta.helm.sh/release-name: plus-nap-kic
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2020-10-26T20:37:32Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: plus-nap-kic
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: plus-nap-kic-nginx-ingress
    helm.sh/chart: nginx-ingress-0.7.0
  name: plus-nap-kic-nginx-ingress
  namespace: default
  resourceVersion: "5420"
  selfLink: /apis/apps/v1/namespaces/default/deployments/plus-nap-kic-nginx-ingress
  uid: 777eee2d-23af-4d0a-9f97-af39b8107e38
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: plus-nap-kic-nginx-ingress
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/port: "9113"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: plus-nap-kic-nginx-ingress
    spec:
      hostNetwork: true
      containers:
      - args:
        - -nginx-plus=true
        - -nginx-reload-timeout=0
        - -enable-app-protect=true
        - -nginx-configmaps=$(POD_NAMESPACE)/plus-nap-kic-nginx-ingress
        - -default-server-tls-secret=$(POD_NAMESPACE)/plus-nap-kic-nginx-ingress-default-server-secret
        - -ingress-class=nginx
        - -health-status=false
        - -health-status-uri=/nginx-health
        - -nginx-debug=false
        - -v=1
        - -nginx-status=true
        - -nginx-status-port=8080
        - -nginx-status-allow-cidrs=0.0.0.0
        - -report-ingress-status
        - -external-service=plus-nap-kic-nginx-ingress
        - -enable-leader-election=true
        - -leader-election-lock-name=plus-nap-kic-nginx-ingress-leader-election
        - -enable-prometheus-metrics=true
        - -prometheus-metrics-listen-port=9113
        - -enable-custom-resources=true
        - -enable-tls-passthrough=false
        - -enable-snippets=false
        - -ready-status=true
        - -ready-status-port=8081
        - -enable-latency-metrics=true
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: jgoodier/kic-190-nap:1.9.0
        imagePullPolicy: IfNotPresent
        name: plus-nap-kic-nginx-ingress
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        - containerPort: 9113
          name: prometheus
          protocol: TCP
        - containerPort: 8081
          name: readiness-port
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /nginx-ready
            port: readiness-port
            scheme: HTTP
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          runAsUser: 101
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: plus-nap-kic-nginx-ingress
      serviceAccountName: plus-nap-kic-nginx-ingress
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2020-10-26T20:37:32Z"
    lastUpdateTime: "2020-10-26T20:37:32Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2020-10-26T20:37:32Z"
    lastUpdateTime: "2020-10-26T20:37:32Z"
    message: ReplicaSet "plus-nap-kic-nginx-ingress-55c9c8df9" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
