apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookinfo-ingress
  namespace: default
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - bookinfo.nginx.rocks
    secretName: nginx-rocks-cert
  rules:
    - host: bookinfo.nginx.rocks
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: productpage
                port:
                  number: 9080                 
